# Welcome to Jekyll!

# Website settings
title: PerennaSec
description: Blog & Portfolio Powered by Jekyll & GitHub Pages.
keywords: PerennaSec,Perenna,blog,security,cloud,automation,linux,python,bash,siem,suricata,splunk,career,github,gh-pages
baseurl:  /home # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://perennasec.github.io/home  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /home/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Spencer Treece | PNPT | Sec+ | Information Security Consultant  # Be used at blog posts' author.
  first_name: Spencer  # Be used at index page about me section.
  last_name: Treece  # Be used at index page about me section.
  avatar: /static/assets/img/landing/profpic200.jpg  # upload your avatar at directory and edit it.
  github_username: PerennaSec  # Leave blank if you don't have now
  linkedin_id: perennasec # Leave blank if you don't have now
  facebook_username:  # Leave blank if you don't have now
  twitter_username:  # Leave blank if you don't have now
  email: perennasec@tutanota.com  # Leave blank if you don't have now
  cv: https://www.linkedin.com/in/perennasec # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Chicago native, professional creative, proven leader, and task master. Currently driving towards Azure security competency. 
  After a decade in the Culinary Industry, including six years of leadership, I made a pivot to the burgeoning field of Cybersecurity. One summer and four certifications later, I was deeply fortunate to land a dream position within the IT Security Practice at Berry Dunn. Now pursuing my passion and actively assisting clients in evaluating and remediating their security posture! 
  Reach me at perennasec@tutanota.com, or simply feel free to message me. I am a lifelong learner, a voracious and driven operator, and a firm believer in the merits of work, discipline, and devotion! # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: cesiuqelzhijk

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: G-SFZKLDYMVH

## google optimize
go:
  #id: 

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

